# Generated by Django 4.1.1 on 2022-10-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('numSocio', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('rut', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('00', 'Sin Tipo Asignado'), ('01', 'Epico'), ('02', 'Terror'), ('03', 'Novela'), ('04', 'Revista'), ('05', 'Ficcion')], default='00', max_length=2)),
                ('editorial', models.CharField(choices=[('00', 'Generica'), ('01', 'Santillana'), ('02', 'ZigZag'), ('03', 'ContraPunto'), ('04', 'Antartica'), ('05', 'UTFSM')], default='00', max_length=2)),
                ('anio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lector')),
            ],
        ),
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('00', 'Disponible'), ('01', 'Prestado'), ('02', 'No Disponible')], default='00', max_length=2)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=10)),
                ('fechaNacimiento', models.DateField()),
                ('libros', models.ManyToManyField(to='app.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.prestamo')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lector')),
            ],
        ),
    ]
