# Generated by Django 4.1.1 on 2022-10-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prestamo_copias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copia',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='lector',
        ),
        migrations.RemoveField(
            model_name='multa',
            name='prestamo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='copias',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='lector',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Copia',
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Multa',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
